>>> for i in range(10):
...     list1.append(i)
... 
>>> list1
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> list2 = []
>>> for i in range(5):
...     list2.append(i)
... 
>>> list2
[0, 1, 2, 3, 4]
>>> list2 ==list1
False
>>> list1.__add__(list2)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4]
>>> list2
[0, 1, 2, 3, 4]
>>> list1
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> list3 = list1.__add__(list2)
>>> list3
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4]
>>> list4= list3__contains__(list2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'list3__contains__' is not defined
>>> list4= list3.__contains__(list2)
>>> list4
False
>>> list2
[0, 1, 2, 3, 4]
>>> list3
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4]
>>> list4 = list2.__contains__(list3)
>>> list4
False
>>> list4= len(list1)
>>> list4
10
>>> list1
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> list2
[0, 1, 2, 3, 4]
>>> list3
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4]
>>> list4
10
>>> list4=list3.count(5)
>>> list4
1
>>> for i in range(10):
...     print(list3.count(i))
... 
2
2
2
2
2
1
1
1
1
1
>>> list3
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4]
>>> list2
[0, 1, 2, 3, 4]
>>> list1
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> list4
1
>>> list4=list2.extend(list2)
>>> list
<class 'list'>
>>> list4
>>> list2
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
>>> list4
>>> list2.index(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: 5 is not in list
>>> list2.index(1)
1
>>> for i in range(5):
...     print(list2.index(i))
... 
0
1
2
3
4
>>> for i in range(5,10):
...     print(list2.index(i))
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ValueError: 5 is not in list
>>> list2
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
>>> list2.insert(5,6)
>>> list2
[0, 1, 2, 3, 4, 6, 0, 1, 2, 3, 4]
>>> list2.insert(5,list4)
>>> list2
[0, 1, 2, 3, 4, None, 6, 0, 1, 2, 3, 4]
>>> list2.insert(5,list1)
>>> list2
[0, 1, 2, 3, 4, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], None, 6, 0, 1, 2, 3, 4]
>>> list2.pop(5)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> list2
[0, 1, 2, 3, 4, None, 6, 0, 1, 2, 3, 4]
>>> list2.index(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: 5 is not in list
>>> list.index(4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: descriptor 'index' requires a 'list' object but received a 'int'
>>> for i in range(5):
...     print(list2.index(i))
... 
0
1
2
3
4
>>> list2.insert(5,abc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'abc' is not defined
>>> list2.insert(5,list4)
>>> list2.index(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: 5 is not in list
